M48
; DRILL file {KiCad 9.0.0} date 2025-03-28T16:29:38+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-28T16:29:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1063
%
G90
G05
T1
X0.9961Y1.9833
T2
X0.6209Y1.9087
X0.6209Y1.6331
T3
X1.7835Y1.9833
T4
X1.9272Y2.0276
X1.9272Y2.0276
X1.9272Y0.1378
X1.9272Y0.1378
M30
